const packageManagement = [
  {
    id: 1,
    calorie_count: '900 - 1000',
    package_name: 'Alden Tate',
    number_of_breakfasts: '174',
    number_of_lunches: '857',
    number_of_authorities: '187',
    number_of_snacks: '733',
    week: true,
    subscription_price: '356',
    subscription_discount: 'Fuga Libero volupta',
    two_weeks: true,
    month: true,
  },
  {
    id: 2,
    calorie_count: '600 - 1500',
    package_name: 'Deborah Mcneil',
    number_of_breakfasts: '874',
    number_of_lunches: '905',
    number_of_authorities: '32',
    number_of_snacks: '56',
    week: true,
    subscription_price: '868',
    subscription_discount: 'Sint consectetur se',
    two_weeks: true,
    month: true,
  },
  {
    id: 3,
    calorie_count: '920 - 2000',
    package_name: 'Nolan Burnett',
    number_of_breakfasts: '215',
    number_of_lunches: '397',
    number_of_authorities: '475',
    number_of_snacks: '611',
    week: true,
    subscription_price: '125',
    subscription_discount: 'Similique vel ea est',
    two_weeks: true,
    month: true,
  },
];

export default packageManagement;
